name: Bake time

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *" # Runs every 1 hour

permissions:
  checks: write

jobs:
  baking_pull_request:
    name: "Baking pull request..."
    runs-on: ubuntu-latest
    steps:
      - uses: peternied/bake-time@1a01d1e993bcaeba380d7ec84340c64fc586a754
        with:
          check-name: "Baking pull request..."
          delay-hours: 48
